# Global variable bindings ------------------------------------------------
utils::globalVariables(c("year", "code", "v", "k", "uv", "mean_diff", "i",
                         "extreme", "j", "v_share", "gamme_fontagne_1997",
                         "med_ref_ijkt", "v_t_k_i", "market_share_t_k_i",
                         "v_t_k_i_j", "market_share_t_k_i_j", "country_code",
                         "country_iso3", "chapter", "total_v_without_outliers",
                         "total_q_without_outliers", "total_v", "total_q",
                         "ratio_v", "ratio_q", "quantile_H", "ratio_value",
                         "iso_region", "name_region", "density", "ecart_type",
                         "median_ikt", "lag_ijk", "lead_ijk", "poids",
                         "importer", "med_ref_t_k", "exporter_iso_region",
                         "importer_iso_region", "total_import_k", "DA",
                         "DA_2010", "DA_100", "DA_diff", "DA_100_exporter_ref",
                         "uv_mean", "uv_year_ref", "uv_100", "sector",
                         "uv_100_exporter_ref", "iso3_o", "iso3_d", "HS6",
                         "sigma", "exporter", "p", "epsilon", "quality"))
